View for JScholarship Redirects
jhu-idc/idc-isle-dc pull request #286
Opened 2021-12-15 22:11 UTC by little9

This adds a View for exporting a file that is similar
to the format used by Apache's RewriteMap.

To access the endpoint for this view:

```
curl -X GET https://test.digital.library.jhu.edu/jscholarship_redirects_rest\?query=\(ss_type\:islandora_object\)\&items_per_page\=500\&offset\=0 > out.csv
```

That will only get the first 500 items. You'll want to use the offset parameter
to go through until you have exported metadata for all the items in the repo.

This would preferably be done in a script.

The resulting file will look like:

```
dspace_identifier "Citable URL"
https://jscholarship.library.jhu.edu/handle/1774.2/57496 https://test.digital.library.jhu.edu/node/5321
```

To use the resulting file as a RewriteMap the headers should be removed and the root URL
should be removed from the jscholarship URLS:

```
/handle/1774.2/57496 https://test.digital.library.jhu.edu/node/5321
```

Then in the JScholarship Apache config (after moving the file to `/etc/httpd/conf/redirects.txt`):

```
  RewriteEngine On
  RewriteMap redirects "txt:/etc/httpd/conf/redirects.txt"
  RewriteCond ${redirects:$1} !=""
  RewriteRule ^(.*)$ ${redirects:$1} [redirect=permanent,last]
```

2021-12-20 20:15 UTC, bseeger commented
When I ran the above curl statement against the cloud test instance I get records like this (**with spaces as separator)**: 
```
dspace_identifier "Citable URL"
https://jscholarship.library.jhu.edu/handle/1774.2/57496 https://test.digital.library.jhu.edu/node/5321
https://jscholarship.library.jhu.edu/handle/1774.2/55393 https://test.digital.library.jhu.edu/node/6472
https://jscholarship.library.jhu.edu/handle/1774.2/55389 https://test.digital.library.jhu.edu/node/6473
https://jscholarship.library.jhu.edu/handle/1774.2/49491 https://test.digital.library.jhu.edu/node/6474
https://jscholarship.library.jhu.edu/handle/1774.2/55376 https://test.digital.library.jhu.edu/node/6475
https://jscholarship.library.jhu.edu/handle/1774.2/49493 https://test.digital.library.jhu.edu/node/6476
https://jscholarship.library.jhu.edu/handle/1774.2/49495 https://test.digital.library.jhu.edu/node/6477
https://jscholarship.library.jhu.edu/handle/1774.2/49494 https://test.digital.library.jhu.edu/node/6478
https://jscholarship.library.jhu.edu/handle/1774.2/55387 https://test.digital.library.jhu.edu/node/6479
```

Running against my local setup with this PR and some test data I get this (**with commas as separator**): 

```
dspace_identifier,"Citable URL"
,https://islandora-idc.traefik.me/node/45
,https://islandora-idc.traefik.me/node/44
http://jscholarship.library.jhu.edu,https://islandora-idc.traefik.me/node/38
http://jscholarship.library.jhu.edu,https://islandora-idc.traefik.me/node/39
http://jscholarship.library.jhu.edu,https://islandora-idc.traefik.me/node/40
http://jscholarship.library.jhu.edu,https://islandora-idc.traefik.me/node/41
http://jscholarship.library.jhu.edu,https://islandora-idc.traefik.me/node/42
```

I have a few items with no DSpace URl. You'll probably want to add a filter condition on the view to check the DSpace identifier - or maybe you have a different way of skipping the records that do no have DSpace URL's. 

Looks good overall with a few minor things that should probably be changed.

2021-12-20 20:16 UTC, bseeger requested changes
Looks good overall, but needs a few minor tweaks to work as expected.

2022-01-04 18:58 UTC, little9 commented
@bseeger Thanks for catching the separator! I also added a filter for the DSpace identifier.

2022-01-05 13:56 UTC, bseeger commented
I can review this today again.  Note that the test failures are due to a testcafe upgrade and John created a PR to lock in a working version yesterday. https://github.com/jhu-idc/idc-isle-dc/pull/291

2022-01-05 19:29 UTC, bseeger approved these changes
This looks good and works as expected.

2022-01-05 19:53 UTC, bseeger commented
This probably resolves: https://github.com/jhu-idc/iDC-general/issues/450

2022-01-05 20:12 UTC, merged