Content type updates based on feedback
jhu-idc/idc-isle-dc pull request #84
Opened 2021-02-24 20:06 UTC by bseeger

This updates the content types and taxonomies based on feedback from Katie and Michelle. 

Highlights:
- Lots of minor changes to help text and field ordering. 
- Name solution we came up with (Katie, Michelle and Bethany)
    - For person: 
       - Person Preferred Name: Primary Part of Name (Required, 1 only), 255 characters
        - Person Preferred Name: 0+ Rest of Name, 255 characters
        - Person Preferred Name: 0+ Prefix, 255 characters
        - Person Preferred Name: 0+ Suffix, 255 characters
        - Person Preferred Name: 0+ Number, 255 characters
        - Person Preferred Name: 0+ Fuller Name, 255 characters 
        - And make a single, repeatable Alternate field:
          - Person Alternate Name (not required, 0+), 1024 characters (?)
    - For corporate body fields: 
      - Corporate Body: Corporate Name (Required, 1 only) Primary Corporate Name, 255 characters
      - Corporate Body: 0+ Subordinate Name, 255 characters
      - Corporate Body: 0+ Location of Meeting, 255 characters
      - Corporate Body: 0+ Date of meeting or treating signing, 255 characters
      - Corporate Body: 0+ Number of section or meeting, 255 characters
      - And make a single, repeatable alternate field: 
        - Alternate Corporate Body (not required;0+), 1024 characters (?)
- Tweaks to EDTF formatting - words it uses when displaying intervals and  (in controlled_access_terms)
- Tweaks to where the help text is put (above or below the fields) (in islandora_defaults)
- Updates test code to handle the changes.

2021-02-25 13:14 UTC, bseeger commented
I need to rebase this - as the snapshot is not updated with the latest on dev.

2021-02-26 16:14 UTC, emetsger requested changes
This looks good, tests pass!

My only comment is that there are a number of fields that were modified to accept multiple values, but the test data for these fields contain single values.  If the test data could be updated to contain multiple values, it would insure that these migration pathways are fully tested.


The verification tests would need to be updated as well, to assert the expected number of values equals the actual number, and that the values are equal as well.

2021-02-26 16:14 UTC, emetsger commented on codebase/config/sync/migrate_plus.migration.idc_ingest_taxonomy_corporatebody.yml
> +  field_subordinate_name:
It looks like `field_subordinate_name` is multi-valued; can an additional value be added to the test CSV to insure this migration pathway is tested?

2021-02-26 16:14 UTC, emetsger commented on codebase/config/sync/migrate_plus.migration.idc_ingest_taxonomy_persons.yml
> +  field_preferred_name_fuller_form:
It looks like a number of fields were modified to accept multiple values, for example:
`field_preferred_name_rest`, `preferred_name_prefix`, `preferred_name_fuller_form`, etc.

Can the test CSV be updated to include multiple values to ensure these new migration paths are tested?

2021-03-02 18:36 UTC, emetsger approved these changes
Looks good to me!

2021-03-02 19:10 UTC, merged